#!/bin/sh
#
#  spades-assembly-coverage - compute coverage from contig headers
#  Copyright (C) 2017  Marco van Zwetselaar <io@zwets.it>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Function to exit this script with an error message on stderr
err_exit() {
    echo "$(basename "$0"): $*" >&2
    exit 1
}

# Function to show usage information and exit
usage_exit() {
    echo "
Usage: $(basename $0) [FILE ...]

  For each FILE compute the weighted average coverage from the length
  and coverage fields in the contig headers produced by SPAdes.  If no
  FILE, or FILE is '-', read from standard input.
" >&2
    exit ${1:-1}
}

# Do the work

[ "$1" != "-h" ] && [ "$1" != "--help" ] || usage_exit

printf "Sample\tBases\tLength\tCoverage\n"

if [ $# -eq 0 -o "$1" = "-" ]; then
    awk -v OFS='\t' -v S="-" -F'_' '
        BEGIN{ TB=0; TL=0 }
        /^>/ { L=$4; C=$6; B=L*C; TB=TB+B; TL=TL+L }
        END  { TC = (TB<1E7||TL<1E6) ? TC="***" : TB/TL; 
               print S, int(TB), int(TL), TC }'
else
    for F in "$@"; do
        S="$(basename "$F")"
        S="${S%.*}"
        awk -v OFS='\t' -v S="$S" -F'_' '
            BEGIN{ TB=0; TL=0 }
            /^>/ { L=$4; C=$6; B=L*C; TB=TB+B; TL=TL+L }
            END  { TC = (TB<1E7||TL<1E6) ? TC="***" : TB/TL; 
                   print S, int(TB), int(TL), TC }
        ' "$F" 
    done
fi

# vim: sts=4:sw=4:et:si:ai
